---
all:
  children:
    iosxe:                       # shared vars for every IOS‑XE device
      vars:
        device_type: "iosxe"
        platform: "iosxe"
        ansible_user: admin
        ansible_password: admin
        ansible_connection: ansible.netcommon.netconf   # use NETCONF transport
        ansible_network_os: cisco.ios.ios               # required for ios_* modules
        port: 830
        ansible_netconf_hostkey_verify: false           # disable SSH key check
      children:
        spine:
          hosts:
            spine1:
              ansible_host: 10.20.0.7
              switch_id: 7
              node_id: 1
            spine2:
              ansible_host: 10.20.0.8
              switch_id: 8
              node_id: 2
        leaf:
          hosts:
            leaf1:
              ansible_host: 10.20.0.9
              switch_id: 9
              node_id: 1
            leaf2:
              ansible_host: 10.20.0.10
              switch_id: 10
              node_id: 2

